openapi: 3.1.0
info:
  title: Workspaces
  description: Needs a description.
paths:
  /api/v2/workspaces:
    get:
      operationId: ListWorkspaces
      tags:
        - Workspaces
      summary: Get  Api V2 Workspaces
      description: |
        #### Allowed For

        * Admins, Agents
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceResponse'
              examples:
                default:
                  value:
                    count: 1
                    next_page: null
                    previous_page: null
                    workspaces:
                      - activated: true
                        apps:
                          - expand: false
                            id: 360000080413
                            position: 1
                        conditions:
                          all:
                            - field: ticket_form_id
                              operator: is
                              value: '360000014173'
                          any: []
                        created_at: '2018-11-13T19:08:13Z'
                        description: Test rules
                        id: 3133
                        macro_ids:
                          - 360005374974
                        position: 1
                        prefer_workspace_app_order: true
                        selected_macros:
                          - actions:
                              - field: status
                                value: solved
                            active: true
                            created_at: '2018-02-08T23:45:30Z'
                            description: null
                            id: 360005374974
                            position: 9999
                            restriction:
                              id: 360002226093
                              ids:
                                - 360002226093
                              type: Group
                            title: Close and redirect to topics
                            updated_at: '2018-11-08T22:27:00Z'
                            url: >-
                              https://{subdomain}.zendesk.com/api/v2/macros/360005374974.json
                            usage_7d: 0
                        ticket_form_id: 360000014173
                        title: Test Workspace 1
                        updated_at: '2018-12-17T22:37:40Z'
                        url: https://{subdomain}.zendesk.com/api/v2/workspaces.json
    post:
      operationId: CreateWorkspace
      tags:
        - Workspaces
      summary: Post  Api V2 Workspaces
      description: |
        #### Allowed For

        * Admins
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workspace:
                  $ref: '#/components/schemas/WorkspaceInput'
            examples:
              default:
                value:
                  workspace:
                    conditions:
                      all:
                        - field: ticket_form_id
                          operator: is
                          value: '360000014173'
                      any: []
                    description: Test rules
                    macros:
                      - 360005374974
                    ticket_form_id: 360000014173
                    title: Test Workspace 1
      responses:
        '201':
          description: Created workspace
          content:
            application/json:
              schema:
                type: object
                properties:
                  workspace:
                    $ref: '#/components/schemas/WorkspaceObject'
              examples:
                default:
                  value:
                    workspace:
                      activated: true
                      apps: []
                      conditions:
                        all:
                          - field: ticket_form_id
                            operator: is
                            value: '360000014173'
                        any: []
                      created_at: '2018-11-13T19:08:13Z'
                      description: Test rules
                      id: 3133
                      macro_ids:
                        - 360005374974
                      position: 1
                      prefer_workspace_app_order: true
                      selected_macros:
                        - actions:
                            - field: status
                              value: solved
                          active: true
                          created_at: '2018-02-08T23:45:30Z'
                          description: null
                          id: 360005374974
                          position: 9999
                          restriction:
                            id: 360002226093
                            ids:
                              - 360002226093
                            type: Group
                          title: Close and redirect to topics
                          updated_at: '2018-11-08T22:27:00Z'
                          url: >-
                            https://{subdomain}.zendesk.com/api/v2/macros/360005374974.json
                          usage_7d: 0
                      ticket_form_id: 360000014173
                      title: Test Workspace 1
                      updated_at: '2018-12-17T22:37:40Z'
                      url: https://{subdomain}.zendesk.com/api/v2/workspaces.json
  /api/v2/workspaces/{workspace_id}:
    parameters:
      - $ref: '#/components/parameters/WorkspaceId'
    get:
      operationId: ShowWorkspace
      tags:
        - Workspaces
      summary: Get  Api V2 Workspaces Workspace_id
      description: |
        #### Allowed For
        * Admins
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  workspace:
                    $ref: '#/components/schemas/WorkspaceObject'
              examples:
                default:
                  value:
                    workspace:
                      activated: true
                      apps: []
                      conditions:
                        all:
                          - field: ticket_form_id
                            operator: is
                            value: '360000014173'
                        any: []
                      created_at: '2018-11-13T19:08:13Z'
                      description: Test rules
                      id: 3133
                      macro_ids:
                        - 360005374974
                      position: 1
                      prefer_workspace_app_order: true
                      selected_macros:
                        - actions:
                            - field: status
                              value: solved
                          active: true
                          created_at: '2018-02-08T23:45:30Z'
                          description: null
                          id: 360005374974
                          position: 9999
                          restriction:
                            id: 360002226093
                            ids:
                              - 360002226093
                            type: Group
                          title: Close and redirect to topics
                          updated_at: '2018-11-08T22:27:00Z'
                          url: >-
                            https://{subdomain}.zendesk.com/api/v2/macros/360005374974.json
                          usage_7d: 0
                      ticket_form_id: 360000014173
                      title: Test Workspace 1
                      updated_at: '2018-12-17T22:37:40Z'
                      url: https://{subdomain}.zendesk.com/api/v2/workspaces.json
    put:
      operationId: UpdateWorkspace
      tags:
        - Workspaces
      summary: Put  Api V2 Workspaces Workspace_id
      description: |-
        #### Allowed For
        * Admins
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workspace:
                  $ref: '#/components/schemas/WorkspaceInput'
            examples:
              default:
                value:
                  workspace:
                    conditions:
                      all:
                        - field: ticket_form_id
                          operator: is
                          value: '360000014173'
                      any: []
                    description: Test rules
                    macros:
                      - 360005374974
                    ticket_form_id: 360000014173
                    title: Test Workspace 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  workspace:
                    $ref: '#/components/schemas/WorkspaceObject'
              examples:
                default:
                  value:
                    workspace:
                      activated: true
                      apps: []
                      conditions:
                        all:
                          - field: ticket_form_id
                            operator: is
                            value: '360000014173'
                        any: []
                      created_at: '2018-11-13T19:08:13Z'
                      description: Test rules
                      id: 3133
                      macro_ids:
                        - 360005374974
                      position: 1
                      prefer_workspace_app_order: true
                      selected_macros:
                        - actions:
                            - field: status
                              value: solved
                          active: true
                          created_at: '2018-02-08T23:45:30Z'
                          description: null
                          id: 360005374974
                          position: 9999
                          restriction:
                            id: 360002226093
                            ids:
                              - 360002226093
                            type: Group
                          title: Close and redirect to topics
                          updated_at: '2018-11-08T22:27:00Z'
                          url: >-
                            https://{subdomain}.zendesk.com/api/v2/macros/360005374974.json
                          usage_7d: 0
                      ticket_form_id: 360000014173
                      title: Test Workspace 1
                      updated_at: '2018-12-17T22:37:40Z'
                      url: https://{subdomain}.zendesk.com/api/v2/workspaces.json
    delete:
      operationId: DeleteWorkspace
      tags:
        - Workspaces
      summary: Delete  Api V2 Workspaces Workspace_id
      description: |
        #### Allowed For
        * Admins
      responses:
        '204':
          description: No Content
  /api/v2/workspaces/destroy_many:
    delete:
      operationId: DestroyManyWorkspaces
      tags:
        - Workspaces
      summary: Delete  Api V2 Workspaces Destroy_many
      description: |
        #### Allowed For
        * Admins
      parameters:
        - name: ids
          in: query
          description: The ids of the workspaces to delete
          required: true
          schema:
            type: array
            items:
              type: integer
          example:
            - 1
            - 2
            - 3
      responses:
        '200':
          description: Succesful response
          content:
            application/json:
              schema:
                type: string
                description: Empty response
                example: ''
              example: ''
  /api/v2/workspaces/reorder:
    put:
      operationId: ReorderWorkspaces
      tags:
        - Workspaces
      summary: Put  Api V2 Workspaces Reorder
      description: |
        #### Allowed For
        * Admins
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: number
            examples:
              default:
                value:
                  ids:
                    - 12
                    - 32
                    - 48
                    - 60
      responses:
        '200':
          description: Succesful response
          content:
            application/json:
              schema:
                type: string
                description: Empty response
                example: ''
              example: ''
components:
  schemas:
    WorkspaceResponse:
      type: object
      allOf:
        - type: object
          properties:
            workspaces:
              type: array
              items:
                $ref: '#/components/schemas/WorkspaceObject'
        - $ref: '#/components/schemas/OffsetPaginationObject'
